<html>
	<head>
		<title>5</title>
		<meta charSet="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" type="text/css" href="/css/bootstrap.css">
		<link rel="stylesheet" type="text/css" href="/css/main.css">
	</head>
	<body>
		<div id="main">
			{{html| safe}}
		</div>
		<script src="/js/app.js"></script>                  
	</body>
</html>